name: Build and upload wheels

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - name: Setup pyenv for ${{ matrix.python-version }}
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        MACOSX_DEPLOYMENT_TARGET: 10.13
        PYTHON_CONFIGURE_OPTS: "--enable-framework"
      uses: "gabrielfalcao/pyenv-action@v5"
      with:
          default: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install wheel setuptools
        pip install -r requirements.txt

    - name: Build wheel
      run: |
        export MACOSX_DEPLOYMENT_TARGET=10.13
        MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CCX=clang++ python setup.py bdist_wheel

    - name: Install software
      run: 
        pip install --find-links=${{github.workspace}}/dist/ SimpleCRF_binaries

    - name: Test import
      run: python -c "import denseCRF, maxflow"

    - name: Install deps for demos
      run: pip install SimpleITK pillow matplotlib

    - name: Test maxflow demo
      run: cd ${{github.workspace}}/examples && python demo_maxflow.py 0

    - name: Test denseCRF demo
      run: cd ${{github.workspace}}/examples && python demo_densecrf.py 1

    - name: Test denseCRF 3D demo
      run: cd ${{github.workspace}}/examples && python demo_densecrf.py 1

    - name: Upload Python wheel
      uses: actions/upload-artifact@v2
      with:
        name: Python wheel
        path: ${{github.workspace}}/dist/SimpleCRF_binaries-*.whl
        if-no-files-found: error
