name: Build and upload wheels

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-18.04, macos-10.15]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install wheel setuptools
        pip install -r requirements.txt

    - name: Build wheel
      run: python setup.py bdist_wheel

    - name: Install software
      run: pip install --find-links=${{github.workspace}}/dist/ SimpleCRF

    - name: Test import
      run: python -c "import denseCRF, maxflow"

    - name: Install deps for demos
      run: pip install SimpleITK pillow matplotlib

    - name: Test maxflow demo
      run: cd ${{github.workspace}}/examples && python demo_maxflow.py 0

    - name: Test denseCRF demo
      run: cd ${{github.workspace}}/examples && python demo_densecrf.py 1

    - name: Test denseCRF 3D demo
      run: |
        cd ${{github.workspace}}/examples && python demo_densecrf.py 1
        ls

    - name: Upload Python wheel
      uses: actions/upload-artifact@v2
      with:
        name: Python wheel
        path: ${{github.workspace}}/dist/SimpleCRF-binaries-*.whl
        if-no-files-found: error
